### ISSUE TITLE
Catalina incompatibilities

### ISSUE THREAD

**Issue by u77345** [gesellkammer/rtmidi2#3] opened 2021-11-29 16:29 UTC
The following MacOS incompatibilities found, compared to the Linux behavior:

1. Open calls (`open_port(0), open_port("*"), open_ports("*")`) always return `NonType`
2. `MidiOut().open_virtual_port(str("OUT"))` errors out with TypeError: Argument 'port_name' has incorrect type (expected str, got bytes)

Installed versions are:

Package       Version
------------- ---------
certifi       2021.10.8
Cython        0.29.24
mido          1.2.10
pip           21.2.4
rtmidi-python 0.2.2
rtmidi2       0.9.2
setuptools    58.0.4
wheel         0.37.0

Python 3.8.12 (default, Oct 12 2021, 06:23:56) 
[Clang 10.0.0 ]

Darwin mac-108.local 20.6.0 Darwin Kernel Version 20.6.0: Tue Oct 12 18:33:42 PDT 2021; root:xnu-7195.141.8~1/RELEASE_X86_64 x86_64

**Comment by gesellkammer** [comment] 2021-11-30 05:40
The problem with open_virtual_port (2) is already fixed in git. The other (1) I can't reproduce, but I don't have a macos system. Notice that in the open_port and open_virtual_port always return None. Usage:

```python

from rtmidi2 import *
m = MidiOut()
m.open_virtual_port("out")
```

**Comment by u77345** [comment] 2021-11-30 23:25
The following code works and returns other then None. The reason for this usage is that the app needs multiple midi outputs.

```
m1_in = rtmidi2.MidiIn().open_port("*Launchkey MK2 25 MIDI 1*")
m1_in.callback = callback1
m1_in.ignore_types(False, False, True)

m2_in = rtmidi2.MidiIn().open_port("*Launchkey MK2 25 MIDI 2*")
m2_in.callback = callback2
m2_in.ignore_types(False, False, True) 
```
 
This is the runtime environment:
```
Linux samplerbox 5.10.17-v7+ #1414 SMP Fri Apr 30 13:18:35 BST 2021 armv7l GNU/Linux
Python 3.7.3
midi                    0.2.3    
mido                    1.2.10   
python-rtmidi           1.4.9    
rtmidi-python           0.2.2    
rtmidi2                 0.8.7  
```

**Comment by gesellkammer** [comment] 2021-11-30 23:29
Again, starting from version 0.9.3, open_port and open_ports return None, so they need to be called as in the comment above

**Comment by u77345** [comment] 2021-12-01 00:58
Can you confirm this is how multiple concurrently opened midi outputs are going to be supported:

```
m1 = MidiOut()
m1.openl_port("out1")

m2 = MidiOut()
m2.open_port("out2")

m3 = MidiOut()
m3.open_virtual_port("out3")

```

**Comment by gesellkammer** [comment] 2021-12-01 08:01
Yes. In general you can think of open_port as creating a connection between your client and an already existing client. open_virtual_port just creates a port for other clients to connect to. 

For example:

```python

from rtmidi2 import *

# This creates a connection between MyClient and an already existing client. Behind the scenes
# it might create a virtual_port with a default name, depending on the platform and api used
mout = MidiOut("MyClient")
mout.open_port("alreadyExistingSynth")

# This creates a virtual port and connects it to an already existing client
mout2 = MidiOut("MyClient2")
mout2.open_virtual_port("myport")
mout2.open_port("alreadyExistingSynth")
```

Because of differences between platforms and apis, rtmidi settled on allowing one connection per port and one port per client.

For MidiIn there is an abstraction layer on top of rtmidi itself, MidiInMulti, which allows to set one callback to receive messages from multiple clients. In this case on some platforms this results in multiple MidiIns, each connected to a different client and all feeding to the same callback. MidiInMulti is specific to rtmidi2 (the python package) and is there only for a better usability. The same result can be achieved manually by creating multiple MidiIns and connecting each to a client.

**Closed as completed** 2022-02-24 09:05 UTC
